import { createSlice } from '@reduxjs/toolkit';
// import any actions here

// create slice
export const dummySlice = createSlice({
  name: 'dummy',
  initialState: {},
  reducers: {
    dummyReducer: (state) => {
      return state;
    },
  },
});

// Export the action creators generated by createSlice
export const { dummyReducer } = dummySlice.actions;

// Export the reducer
export default dummySlice.reducer;
